steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sample-httpd:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/sample-httpd:$SHORT_SHA'
  
#retrieve key
- name: 'gcr.io/cloud-builders/gcloud'
  id: retrieve-read-key
  entrypoint: 'bash'
  dir: ${_DIR}  
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret="pf-test-git" --project=identity-pingfed-lab-ef24f2  > /root/.ssh/id_rsa;
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  id: add-github-key
  entrypoint: 'bash'
  dir: ${_DIR}
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  
# This step clones the repository
- name: 'gcr.io/cloud-builders/git'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/chakradharnakka/Pf-demo.git && \
    cd Pf-demo && \
    git checkout main 
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     set -x && \
     cd Pf-demo && \
     sed -i "s#pingidentity/pingfederate:edge#gcr.io/$PROJECT_ID/sample-httpd:$SHORT_SHA#g" k8s/PF-site1-sample_vitalii.yaml k8s/PF-site2-sample_vitalii.yaml
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# This step pushes the manifest back
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    git config --global user.email chakradhar.nakka@telus.com && \
    git config --global user.name "chakradharnakka" && \
    cd Pf-demo && \
    git add k8s/ && \
    git status && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/sample-httpd:${SHORT_SHA} Built from commit ${COMMIT_SHA} of repository PF-demo" && \
    git push
  volumes:
  - name: 'ssh'
    path: /root/.ssh

    
